define('C_PHP_BS_GRID_DEFAULT_PAGE_NUM', 1);
define('C_PHP_BS_GRID_DEFAULT_ROWS_PER_PAGE', 10);
define('C_PHP_BS_GRID_COLUMNS_DEFAULT', 1);
define('C_PHP_BS_GRID_COLUMNS_MORE', 2);
define('C_PHP_BS_GRID_DEFAULT_SHORT_ADVANCED', 2);

define('C_PHP_BS_GRID_CRITERIA_TEXT_IGNORE', 1);
define('C_PHP_BS_GRID_CRITERIA_TEXT_EQUAL', 2);
define('C_PHP_BS_GRID_CRITERIA_TEXT_STARTS_WITH', 3);
define('C_PHP_BS_GRID_CRITERIA_TEXT_CONTAINS', 4);
define('C_PHP_BS_GRID_CRITERIA_TEXT_IS_NULL', 5);

define('C_PHP_BS_GRID_CRITERIA_LOOKUP_IGNORE', 1);
define('C_PHP_BS_GRID_CRITERIA_LOOKUP_EQUAL', 2);
define('C_PHP_BS_GRID_LOOKUP_IS_NULL', 3);

define('C_PHP_BS_GRID_CRITERIA_DATE_IGNORE', 1);
define('C_PHP_BS_GRID_CRITERIA_DATE_EQUAL', 2);
define('C_PHP_BS_GRID_CRITERIA_DATE_LESS_THAN_OR_EQUAL_TO', 3);
define('C_PHP_BS_GRID_CRITERIA_DATE_GREATER_THAN_OR_EQUAL_TO', 4);
define('C_PHP_BS_GRID_CRITERIA_DATE_IS_NULL', 5);

define('C_PHP_BS_GRID_EXPORT_CSV_NONE', 1);
define('C_PHP_BS_GRID_EXPORT_CSV_ENCODING_DEFAULT', 2);
define('C_PHP_BS_GRID_EXPORT_CSV_ENCODING_UTF8', 3);
